name: Deploy Next.js App to Pages

run-name: ${{ github.actor }} is deploying

on:
  push:
    branches:
      - main
  
   # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-web-app:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    concurrency:
      group: pages
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4
        with:
          version: 11

      - uses: actions/setup-node@v7
        with:
          node-version: '24'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --allow-scripts=unrs-resolver

      - name: Build web-app
        working-directory: ./apps/web-app
        run: pnpm build
        env:
          NEXT_PUBLIC_BASE_PATH: /paddlepit

      - uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./apps/web-app/out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
